import {db,settings,initialize,cleanup,session,saveProgress,progress,record,maxUser,validate,publicRecord,cookie} from '@/lib/server';
export const dynamic='force-dynamic';
function response(data:any,status=200,headers:any={}){return Response.json(data,{status,headers:{'Cache-Control':'no-store',...headers}});}
export async function GET(req:Request){try{await initialize();await cleanup();const s=await session(req);const all=await db().prepare('SELECT * FROM records WHERE deleted=0 ORDER BY updated').all();const rows=all.results.map((r:any)=>s?.admin?{...JSON.parse(r.data),draft:r.draft?JSON.parse(r.draft):null}:publicRecord(JSON.parse(r.data))).filter((r:any)=>s?.admin||!r.unpublished);const p=s?(await db().prepare('SELECT key,data FROM progress WHERE user_id=?').bind(s.user_id).all()).results:[];return response({records:rows,progress:Object.fromEntries(p.map((r:any)=>[r.key,sanitizeProgress(JSON.parse(r.data))])),profile:s?{name:s.name,photo:s.photo,max:s.user_id.startsWith('max:'),admin:!!s.admin}:null,runner:!!settings().RUNNER_URL,maxConnected:!!settings().BOT_TOKEN,demo:settings().DEMO_MODE!=='false'});}catch(e:any){console.error(e);return response({error:e.message},503);}}
export async function POST(req:Request){try{const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)return response({error:'Недопустимый источник'},403);await initialize();const b=await req.json() as any;let s=await session(req);if(b.action==='session'){if(b.initData){const u=await maxUser(b.initData);const token=crypto.randomUUID()+crypto.randomUUID();await db().prepare('INSERT INTO sessions(token,user_id,name,photo,admin,expires) VALUES(?,?,?,?,0,?)').bind(token,'max:'+u.id,u.first_name||u.name||'',u.photo_url||'',Date.now()+86400000*30).run();return response({ok:true},200,{'Set-Cookie':`olympus_session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=2592000; ${new URL(req.url).protocol==='https:'?'Secure':''}`});}if(!s){const token=crypto.randomUUID()+crypto.randomUUID();await db().prepare('INSERT INTO sessions(token,user_id,admin,expires) VALUES(?,?,0,?)').bind(token,'guest:'+crypto.randomUUID(),Date.now()+31536000000).run();return response({ok:true},200,{'Set-Cookie':`olympus_session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=31536000; ${new URL(req.url).protocol==='https:'?'Secure':''}`});}return response({ok:true});}
if(!s)return response({error:'Обновите страницу для начала сеанса'},401);
if(b.action==='admin-login'){const expected=settings().DEMO_MODE==='false'?settings().ADMIN_PASSWORD:'1111';if(!expected||b.password!==expected)return response({error:'Неверный пароль'},403);await db().prepare('UPDATE sessions SET admin=1 WHERE token=?').bind(s.token).run();return response({ok:true});}
if(b.action==='admin-logout'){await db().prepare('UPDATE sessions SET admin=0 WHERE token=?').bind(s.token).run();return response({ok:true});}
if(b.action==='view-lesson'){if((await record(b.id)).kind!=='lessons')throw Error('Урок не найден');await saveProgress(s.user_id,'lesson:'+b.id,{read:true});return response({ok:true});}
if(b.action==='star'){const topic=(await record(b.id)).value;const lessons=(await db().prepare("SELECT id FROM records WHERE kind='lessons' AND deleted=0 AND json_extract(data,'$.topicId')=?").bind(b.id).all()).results;if(!lessons.length)throw Error('В теме пока нет уроков');for(const l of lessons)if(!await progress(s.user_id,'lesson:'+l.id))throw Error('Сначала открой все уроки темы');await saveProgress(s.user_id,'star:'+b.id,{title:topic.title,subject:topic.subject,date:Date.now()});return response({ok:true});}
if(b.action==='register'){await record(b.id);if(b.yes)await saveProgress(s.user_id,'registration:'+b.id,{registered:true});else await db().prepare('DELETE FROM progress WHERE user_id=? AND key=?').bind(s.user_id,'registration:'+b.id).run();return response({ok:true});}
if(b.action==='code-draft'){await saveProgress(s.user_id,'code:'+b.id,{code:String(b.code).slice(0,50000),language:b.language});return response({ok:true});}
if(['check','reveal','hint','run'].includes(b.action)){const task=(await record(b.id)).value;if(b.action==='reveal')return response({answer:task.answer,solution:task.solution});if(b.action==='hint')return response({hint:task.hint||'Разбей условие на шаги и проверь небольшой пример'});let correct=false,output='';if(task.type==='number'){const raw=String(b.answer||'').trim();if(!/^[-+]?\d+(?:[.,]\d+)?$/.test(raw))throw Error('Введите число, например 12 или 0,5');correct=Number(raw.replace(',','.'))===Number(String(task.answer).replace(',','.'));}else if(task.type==='proof')correct=b.correct===true;else{const result=await executeCode(task,b);output=result.output;if(b.action==='run')return response(result);correct=result.correct;}
const old=await progress(s.user_id,'task:'+task.id);await saveProgress(s.user_id,'task:'+task.id,{title:task.title,topicId:task.topicId,subject:task.subject,correct:!!(correct||old?.correct),lastCorrect:correct,attempts:(old?.attempts||0)+1,selfChecked:task.type==='proof'});return response({correct,output});}
if(b.action==='start-mock'){const test=(await record(b.id)).value;if(test.kind!=='mock-tests'||!test.taskIds?.length)throw Error('Пробник пока пуст');const id=crypto.randomUUID();const tasks=[];for(const tid of test.taskIds)tasks.push((await record(tid)).value);const attempt={id,testId:test.id,title:test.title,subject:test.subject,started:Date.now(),ends:Date.now()+test.minutes*60000,tasks,answers:{},finished:false};await saveProgress(s.user_id,'attempt:'+id,attempt);return response({attempt:{...attempt,tasks:tasks.map(publicRecord)}});}
if(b.action==='mock-save'||b.action==='finish-mock'){const key='attempt:'+b.id;const a=await progress(s.user_id,key);if(!a)throw Error('Попытка не найдена');if(a.finished)return response({attempt:a});if(Date.now()<=a.ends){a.answers=b.answers||a.answers;}if(b.action==='mock-save'&&Date.now()<a.ends){await saveProgress(s.user_id,key,a);return response({ok:true});}a.finished=true;a.finishedAt=Date.now();a.results=[];for(const t of a.tasks){const ans=a.answers[t.id];let ok=false;let note='';if(t.type==='number')ok=!!ans&&/^[-+]?\d+(?:[.,]\d+)?$/.test(String(ans).trim())&&Number(String(ans).replace(',','.'))===Number(String(t.answer).replace(',','.'));else if(t.type==='proof')note='Самопроверка после завершения';else if(ans?.code){try{ok=(await executeCode(t,{code:ans.code,language:ans.language,action:'check'})).correct}catch(e:any){note=e.message}}a.results.push({id:t.id,correct:ok,points:ok?Number(t.points??1):0,max:Number(t.points??1),note});}a.score=a.results.reduce((n:number,r:any)=>n+r.points,0);a.max=a.results.reduce((n:number,r:any)=>n+r.max,0);await saveProgress(s.user_id,key,a);return response({attempt:a});}
if(b.action==='mock-proof'){const key='attempt:'+b.id,a=await progress(s.user_id,key);if(!a?.finished)throw Error('Сначала завершите пробник');const t=a.tasks.find((t:any)=>t.id===b.taskId&&t.type==='proof');if(!t)throw Error('Задание не найдено');const r=a.results.find((r:any)=>r.id===t.id);r.correct=!!b.correct;r.points=b.correct?r.max:0;r.note='Самопроверка';a.score=a.results.reduce((n:number,r:any)=>n+r.points,0);await saveProgress(s.user_id,key,a);return response({attempt:a});}
if(!s.admin)return response({error:'Требуется вход администратора'},403);
if(b.action==='history'){const rows=await db().prepare('SELECT * FROM revisions WHERE record_id=? ORDER BY created DESC').bind(b.id).all();return response({history:rows.results.map((r:any)=>({...r,data:JSON.parse(r.data)}))});}
if(b.action==='restore'){const r=await db().prepare('SELECT * FROM revisions WHERE id=?').bind(b.revisionId).first();if(!r)throw Error('Версия не найдена');await db().prepare('UPDATE records SET draft=?,deleted=0 WHERE id=?').bind(r.data,r.record_id).run();return response({ok:true});}
if(b.action==='delete'){await db().batch([db().prepare('INSERT INTO revisions(id,record_id,data,created) SELECT ?,id,data,? FROM records WHERE id=?').bind(crypto.randomUUID(),Date.now(),b.id),db().prepare('UPDATE records SET deleted=1 WHERE id=?').bind(b.id)]);return response({ok:true});}
if(b.action==='deleted'){const rows=await db().prepare('SELECT * FROM records WHERE deleted=1').all();return response({deleted:rows.results.map((r:any)=>JSON.parse(r.data))});}
if(['draft','publish','import'].includes(b.action)){let items=b.action==='import'?b.records:[b.record];if(!Array.isArray(items)||!items.length||items.length>1500)throw Error('Загрузите массив от 1 до 1500 материалов');items=items.map((r:any)=>validate({...r,draft:undefined}));const statements=[];for(const r of items){const data=JSON.stringify(r);if(b.action==='draft'){statements.push(db().prepare('INSERT INTO records(id,kind,data,draft,updated,deleted) VALUES(?,?,?,?,?,0) ON CONFLICT(id) DO UPDATE SET draft=excluded.draft,updated=excluded.updated').bind(r.id,r.kind,JSON.stringify({...r,unpublished:true}),data,Date.now()));}else{statements.push(db().prepare('INSERT INTO revisions(id,record_id,data,created) SELECT ?,id,data,? FROM records WHERE id=?').bind(crypto.randomUUID(),Date.now(),r.id));statements.push(db().prepare('INSERT INTO records(id,kind,data,updated,deleted) VALUES(?,?,?,?,0) ON CONFLICT(id) DO UPDATE SET data=excluded.data,draft=NULL,updated=excluded.updated,deleted=0').bind(r.id,r.kind,data,Date.now()));}}// D1 batch is atomic; reject oversized imports rather than partially applying.
if(statements.length>1800)throw Error('Разделите импорт на файлы до 900 материалов');await db().batch(statements);return response({ok:true,count:items.length});}
if(b.action==='upload'){if(!settings().BUCKET)throw Error('Загрузка файлов недоступна');if(!['image/png','image/jpeg','image/webp','application/pdf','video/mp4'].includes(b.type))throw Error('Поддерживаются PNG, JPG, WebP, PDF и MP4');if(b.base64.length>12000000)throw Error('Файл слишком большой: максимум 8 МБ');const bytes=Uint8Array.from(atob(b.base64),(c:string)=>c.charCodeAt(0));const id=crypto.randomUUID();await settings().BUCKET.put(id,bytes,{httpMetadata:{contentType:b.type}});return response({url:'/api/media/'+id});}
return response({error:'Неизвестное действие'},400);
}catch(e:any){console.error(e);return response({error:e.message||'Не удалось сохранить. Попробуйте ещё раз'},400);}}
async function executeCode(task:any,b:any){if(!settings().RUNNER_URL)throw Error('Сервер выполнения кода ещё не подключён. Код сохранён, проверка станет доступна после подключения');const languages=['python','cpp','java','javascript','kotlin','pascal'];if(!languages.includes(b.language))throw Error('Выберите язык');if(String(b.code).length>50000)throw Error('Код слишком длинный');const tests=b.action==='run'?[{input:String(b.input||''),output:null}]:task.tests;const r=await fetch(settings().RUNNER_URL+'/execute',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+settings().RUNNER_TOKEN},body:JSON.stringify({code:b.code,language:b.language,tests}),signal:AbortSignal.timeout(55000)});const result:any=await r.json();if(!r.ok)throw Error(result.error||'Сервер выполнения временно недоступен');return result;}

function sanitizeProgress(p:any){if(p?.tasks&&!p.finished)return {...p,tasks:p.tasks.map(publicRecord)};return p;}
