import {env} from 'cloudflare:workers';
import seed from './seed.json';
export const settings=()=>env as any;
export const db=()=>{const d=settings().DB;if(!d)throw Error('Хранилище временно недоступно');return d;};
export async function digest(value:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))).map(x=>x.toString(16).padStart(2,'0')).join('');}
let initialized:Promise<void>|undefined;
export async function initialize(){if(!initialized)initialized=(async()=>{const hash=await digest(JSON.stringify(seed));const old=await db().prepare('SELECT hash FROM imports WHERE id=?').bind('bundle').first();if(old?.hash!==hash){for(let i=0;i<seed.length;i+=25){const batch=[];for(const r of (seed as any[]).slice(i,i+25)){const data=JSON.stringify(r),h=await digest(data);const known=await db().prepare('SELECT hash FROM imports WHERE id=?').bind(r.id).first();if(known?.hash===h)continue;batch.push(db().prepare('INSERT INTO revisions(id,record_id,data,created) SELECT ?,id,data,? FROM records WHERE id=?').bind(crypto.randomUUID(),Date.now(),r.id));batch.push(db().prepare('INSERT INTO records(id,kind,data,updated,deleted) VALUES(?,?,?,?,0) ON CONFLICT(id) DO UPDATE SET kind=excluded.kind,data=excluded.data,draft=NULL,updated=excluded.updated,deleted=0').bind(r.id,r.kind,data,Date.now()));batch.push(db().prepare('INSERT INTO imports(id,hash) VALUES(?,?) ON CONFLICT(id) DO UPDATE SET hash=excluded.hash').bind(r.id,h));}if(batch.length)await db().batch(batch);}await db().prepare('INSERT INTO imports(id,hash) VALUES(?,?) ON CONFLICT(id) DO UPDATE SET hash=excluded.hash').bind('bundle',hash).run();}})().catch(e=>{initialized=undefined;throw e});await initialized;}
export async function cleanup(){const date=new Date().toLocaleDateString('en-CA',{timeZone:'Europe/Moscow'});const old=await db().prepare("SELECT id FROM records WHERE kind='olympiads' AND deleted=0 AND json_extract(data,'$.date') < ?").bind(date).all();for(const r of old.results||[])await db().batch([db().prepare('DELETE FROM progress WHERE key=?').bind('registration:'+r.id),db().prepare('DELETE FROM revisions WHERE record_id=?').bind(r.id),db().prepare('DELETE FROM records WHERE id=?').bind(r.id)]);}
export function cookie(req:Request,name:string){return req.headers.get('cookie')?.split(';').map(x=>x.trim()).find(x=>x.startsWith(name+'='))?.slice(name.length+1)||'';}
export async function session(req:Request){const token=cookie(req,'olympus_session');return token?db().prepare('SELECT * FROM sessions WHERE token=? AND expires>?').bind(token,Date.now()).first():null;}
export async function saveProgress(uid:string,key:string,data:any){await db().prepare('INSERT INTO progress(user_id,key,data,updated) VALUES(?,?,?,?) ON CONFLICT(user_id,key) DO UPDATE SET data=excluded.data,updated=excluded.updated').bind(uid,key,JSON.stringify(data),Date.now()).run();}
export async function progress(uid:string,key:string){const r=await db().prepare('SELECT data FROM progress WHERE user_id=? AND key=?').bind(uid,key).first();return r?JSON.parse(r.data):null;}
export async function record(id:string){const r=await db().prepare('SELECT * FROM records WHERE id=? AND deleted=0').bind(id).first();if(!r)throw Error('Материал не найден');return {...r,value:JSON.parse(r.data)};}
export async function hmac(key:Uint8Array,data:string){const k=await crypto.subtle.importKey('raw',key as BufferSource,{name:'HMAC',hash:'SHA-256'},false,['sign']);return new Uint8Array(await crypto.subtle.sign('HMAC',k,new TextEncoder().encode(data)));}
export async function maxUser(init:string){const token=settings().BOT_TOKEN;if(!token)throw Error('Вход MAX пока не подключён: нужен токен бота организаторов');const p=new URLSearchParams(init);const keys=[...p.keys()];if(new Set(keys).size!==keys.length||!p.has('hash'))throw Error('Неверные данные MAX');const hash=p.get('hash');p.delete('hash');const age=Date.now()/1000-Number(p.get('auth_date'));if(age>3600||age< -30||!Number.isFinite(age))throw Error('Открой приложение заново через MAX');p.sort();const secret=await hmac(new TextEncoder().encode('WebAppData'),token);const check=await hmac(secret,[...p].map(([k,v])=>`${k}=${v}`).join('\n'));const result=[...check].map(x=>x.toString(16).padStart(2,'0')).join('');if(result!==hash)throw Error('Подпись MAX не прошла проверку');const user=JSON.parse(p.get('user')||'{}');if(!user.id)throw Error('Нет профиля MAX');return user;}
export function safeURL(s:string){if(!s)return '';if(s.startsWith('/api/media/')||/^\/materials\/[a-zA-Z0-9_./-]+$/.test(s)&&!s.includes('..'))return s;try{const u=new URL(s);if(u.protocol==='https:')return s;}catch{}throw Error('Ссылка должна начинаться с https://');}
export function validate(r:any){if(!r||!['topics','lessons','tasks','olympiads','mock-tests'].includes(r.kind))throw Error('Неизвестный тип материала');if(!/^[a-zA-Z0-9_-]{1,100}$/.test(r.id||''))throw Error('ID: латинские буквы, цифры, дефис');if(!r.title?.trim())throw Error('Укажите название');if(r.kind==='tasks'){if(!['number','proof','code'].includes(r.type))throw Error('Выберите тип задания');if(!r.prompt?.trim()||!r.solution?.trim())throw Error('Нужны условие и разбор');if(r.type==='number'&&!/^[-+]?\d+(?:[.,]\d+)?$/.test(String(r.answer)))throw Error('Введите числовой правильный ответ');if(r.type==='code'&&(!r.tests?.length||r.tests.some((t:any)=>typeof t.input!=='string'||typeof t.output!=='string')))throw Error('Добавьте вход и правильный выход для тестов');}if(r.url)safeURL(r.url);if(r.kind==='lessons')for(const b of r.blocks||[])if(['image','video','link'].includes(b.type))safeURL(b.value);if(r.grade&&! [4,5,6].includes(Number(r.grade)))throw Error('Класс от 4 до 6');if(r.kind==='mock-tests'&&(!(r.minutes>0)||!r.taskIds?.length))throw Error('Нужно время и хотя бы одно задание');if(r.kind==='olympiads'&&(!/^\d{4}-\d{2}-\d{2}$/.test(r.date)||!/^\d{4}-\d{2}-\d{2}$/.test(r.deadline)||r.deadline>r.date))throw Error('Проверьте даты регистрации и проведения');return r;}
export function publicRecord(r:any){const o={...r};if(o.kind==='tasks'){delete o.answer;delete o.tests;delete o.solution;delete o.hint;}return o;}
