// Adapter to a separately deployed Judge0 CE sandbox. Never executes code here.
import http from 'node:http';
import {timingSafeEqual} from 'node:crypto';
const url=process.env.JUDGE0_URL,token=process.env.RUNNER_TOKEN;
if(!url||!token)throw Error('Set JUDGE0_URL and RUNNER_TOKEN');
const patterns={python:/^Python \(3/,cpp:/^C\+\+/,java:/^Java \(/,javascript:/^JavaScript/,kotlin:/^Kotlin/,pascal:/^Pascal/};
const headers={'Content-Type':'application/json',...(process.env.JUDGE0_AUTH_TOKEN?{'X-Auth-Token':process.env.JUDGE0_AUTH_TOKEN}:{})};
let languages;
async function judge(path,body){const r=await fetch(url.replace(/\/$/,'')+path,{method:body?'POST':'GET',headers,body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(45000)});if(!r.ok)throw Error('Сервис проверки недоступен');return r.json();}
const normalize=s=>String(s??'').trim().replace(/\s+/g,' ');
let active=0;
http.createServer(async(req,res)=>{const send=(status,data)=>{res.writeHead(status,{'Content-Type':'application/json'});res.end(JSON.stringify(data))};if(req.url==='/health')return send(200,{ok:true});const auth=Buffer.from(req.headers.authorization||''),expected=Buffer.from('Bearer '+token);if(auth.length!==expected.length||!timingSafeEqual(auth,expected))return send(403,{error:'Forbidden'});if(req.url!=='/execute'||req.method!=='POST')return send(404,{error:'Not found'});if(active>=4)return send(429,{error:'Занято, попробуйте позже'});active++;try{let body='';for await(const chunk of req){body+=chunk;if(body.length>1000000)throw Error('Запрос слишком большой')}const b=JSON.parse(body);if(!patterns[b.language]||typeof b.code!=='string'||b.code.length>50000||!Array.isArray(b.tests)||!b.tests.length||b.tests.length>20)throw Error('Неверное задание');languages??=await judge('/languages');const lang=languages.filter(x=>patterns[b.language].test(x.name)).sort((a,b)=>b.id-a.id)[0];if(!lang)throw Error('Этот язык ещё не установлен на сервере');let correct=true,output='',passed=0;const practice=b.tests.length===1&&b.tests[0].output===null;
for(const test of b.tests){const sub=await judge('/submissions?base64_encoded=false&wait=false',{source_code:b.code,language_id:lang.id,stdin:test.input,cpu_time_limit:2,wall_time_limit:5,memory_limit:262144,enable_network:false,max_file_size:1024});let result;const end=Date.now()+15000;do{await new Promise(r=>setTimeout(r,350));result=await judge('/submissions/'+encodeURIComponent(sub.token)+'?base64_encoded=false');}while(result.status?.id<=2&&Date.now()<end);if(result.status?.id<=2||result.status?.id===5){correct=false;output='Код выполняется слишком долго. Проверьте циклы';break;}if(result.status?.id!==3){correct=false;output=String(result.compile_output||result.stderr||'Проверьте синтаксис и ввод данных').slice(0,10000);break;}const ok=practice||normalize(result.stdout)===normalize(test.output);if(ok)passed++;else correct=false;if(practice)output=String(result.stdout||'').slice(0,10000);}
if(!practice&&!output)output=`Пройдено тестов: ${passed} из ${b.tests.length}`;send(200,{correct,output});}catch(e){send(400,{error:e.message})}finally{active--;}}).listen(8080,'0.0.0.0');
